In [1]:
import pandas as pd

In [7]:
dic={
    "name":["Prince","Prit","Harsh"],
    "CGPA":[7,8,9]
}
df=pd.DataFrame(dic)
print(df)

     name  CGPA
0  Prince     7
1    Prit     8
2   Harsh     9

In [9]:
df

     name  CGPA
0  Prince     7
1    Prit     8
2   Harsh     9

In [17]:
ser=pd.Series([1,2,3,4]) #labeled but with index it self
print(ser)
print(type(ser))
print(ser[0])
print("\n")


ser1=pd.Series([11,22,33],index=["prince","prit","harsh"])  #labeled 
print(ser1)
print(type(ser1))
print(ser1[2])    #it will show warning not error
print(ser1["prit"])
print(ser1.index)  #will print all labels

0    1
1    2
2    3
3    4
dtype: int64
<class 'pandas.core.series.Series'>
1


prince    11
prit      22
harsh     33
dtype: int64
<class 'pandas.core.series.Series'>
33
22
Index(['prince', 'prit', 'harsh'], dtype='object')

C:\Users\princ\AppData\Local\Temp\ipykernel_12252\2292122521.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(ser1[2])    #it will show warning not error

In [26]:
s1=pd.Series([1,2,3,4])
s2=pd.Series([10,20,30,40])
print(s1+s2)  #beacuase of vectorization

s1[0]=100  #mutable values
print(s1.drop(0)) #create new series
print(s1)   #immutable size

s3=pd.Series([1,2,"prime"])  #it will give dtype object because it is homogenous
print(s3)
print(type(s3))

0    11
1    22
2    33
3    44
dtype: int64
1    2
2    3
3    4
dtype: int64
0    100
1      2
2      3
3      4
dtype: int64
0        1
1        2
2    prime
dtype: object
<class 'pandas.core.series.Series'>

In [41]:
#using dictonary
dic1={
    "name":["Prince","Prit","Harsh"],
    "CGPA":[7,8,9]
}
df1=pd.DataFrame(dic1)
print(df1)

print("\n")

#using list of list
list1=pd.DataFrame([[1,"Prince"],[2,"Prit"]],columns=["roll_no","name"])
print(list1)
print(list1.index)
print(list1.columns)

#using Numpy Array

import numpy as np

np_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr=pd.DataFrame(np_array,columns=["A","B","C"])
print(arr)
print(arr.index)
print(arr.columns)

     name  CGPA
0  Prince     7
1    Prit     8
2   Harsh     9


   roll_no    name
0        1  Prince
1        2    Prit
RangeIndex(start=0, stop=2, step=1)
Index(['roll_no', 'name'], dtype='object')
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9
RangeIndex(start=0, stop=3, step=1)
Index(['A', 'B', 'C'], dtype='object')

In [44]:
#import dataset

data=pd.read_csv("raw_data.csv")
print(data)

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [45]:
data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [59]:
#function

print(data.head(),"\n") #first 5 raws
print(data.tail(),"\n") #last 5 raws
print(data.tail(2),"\n") 
print(data.sample(),"\n") #random raw
print(data.info(),"\n") #provide some usefull information
print(data.describe(),"\n") #provide some usefull information of numbers
print(data.shape,"\n") #raw,columns
print(data.columns,"\n") 
print(data.nunique())

   id          name   age country   gender   income
0   1      John Doe  29.0     USA     Male  55000.0
1   1      John Doe  29.0     USA     Male  55000.0
2   2    Jane Smith   NaN  Canada   Female  62000.0
3   3          Alex   NaN     USA  Unknown  47000.0
4   4  Maria Garcia  34.0   Spain   Female      NaN

    id         name   age country  gender   income
6    6          NaN  45.0   India  Female  73000.0
7    7   Ahmed Khan  38.0     NaN    Male  68000.0
8    8   Rachel Lee  29.0     USA  Female  62000.0
9    9  Carlos Ruiz   NaN  Mexico    Male  45000.0
10  10  Emily Davis  31.0     USA     NaN  58000.0

    id         name   age country gender   income
9    9  Carlos Ruiz   NaN  Mexico   Male  45000.0
10  10  Emily Davis  31.0     USA    NaN  58000.0

   id          name   age country  gender  income
4   4  Maria Garcia  34.0   Spain  Female     NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       11 non-null     int64
 1   name     10 non-null     object
 2   age      8 non-null      float64
 3   country  10 non-null     object
 4   gender   10 non-null     object
 5   income   10 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 660.0+ bytes
None

              id        age        income
count  11.000000   8.000000     10.000000
mean    5.090909  32.750000  57600.000000
std     3.176619   6.065123   8896.940798
min     1.000000  27.000000  45000.000000
25%     2.500000  29.000000  52000.000000
50%     5.000000  30.000000  56500.000000
75%     7.500000  35.000000  62000.000000
max    10.000000  45.000000  73000.000000

(11, 6)

Index(['id', 'name', 'age', 'country', 'gender', 'income'], dtype='object')

id         10
name        9
age         6
country     6
gender      3
income      8
dtype: int64

In [3]:
#work on real dataset

data=pd.read_csv("globalAirQuality.csv")
data

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [24]:
print(data.columns)


#use of loc and iloc
print(data.loc[1])          #used for labled index so we can access using lable name
print(data.loc[:2,"city"])  #raw,column
                            #in loc if we use slicing [start:end] then end is included
print("\n")
 #iloc   it is used for index(cannot give lable name)
print(data.iloc[0])
print(data.iloc[:2,2])    #same as print(data.loc[:2,"city"])
print(data.iloc[1,1:3])   #in iloc if we use slicing [start:end] then end is excluded


#use of at and iat
print("\n")
print(data.at[3,"city"])     #use for labaled data 
print(data.iat[3,2])         #use on index only

#it is compulosory to provide value of both raw and column, and only 1 index or name is allowed. else give error

Index(['timestamp', 'country', 'city', 'latitude', 'longitude', 'pm25', 'pm10',
       'no2', 'so2', 'o3', 'co', 'aqi', 'temperature', 'humidity',
       'wind_speed'],
      dtype='object')
timestamp      2025-11-04 19:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                               32.083
pm10                               63.043
no2                                 36.12
so2                                 4.021
o3                                 43.536
co                                  1.075
aqi                                    90
temperature                         5.838
humidity                           80.088
wind_speed                          8.969
Name: 1, dtype: object
0    New York
1    New York
2    New York
Name: city, dtype: object


timestamp      2025-11-04 18:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                               50.295
pm10                              108.938
no2                                27.998
so2                                 6.539
o3                                 52.568
co                                  1.096
aqi                                   108
temperature                        18.504
humidity                           70.168
wind_speed                          3.725
Name: 0, dtype: object
0    New York
1    New York
Name: city, dtype: object
country          US
city       New York
Name: 1, dtype: object


New York
New York

In [48]:
#filter data (me:syntax is complex tc)

new=data[data["aqi"]>100]["city"]
print(new)
new1=data[(data["aqi"]>100) & (data["temperature"]>20)]["city"]
print(new1)

new1.iloc[0]   

#new1.loc[1]  #will give error beacuse there might be possible that lable can be diffrent

0        New York
3        New York
6        New York
7        New York
8        New York
           ...
17991      Zurich
17993      Zurich
17995      Zurich
17996      Zurich
17997      Zurich
Name: city, Length: 9721, dtype: object
3        New York
6        New York
7        New York
8        New York
13       New York
           ...
17985      Zurich
17991      Zurich
17993      Zurich
17996      Zurich
17997      Zurich
Name: city, Length: 5323, dtype: object

'New York'

# 🐼 Pandas `query()` – Quick Notes

- `query()` filters **DataFrame rows** using a **string condition written as a string expression**.   

---

## 🔹 Core Rules

- Condition must be a **string**: `"age > 25"`. 
- Use **column names directly** (no `df['col']` inside the expression).   
- Use **backticks** for columns with spaces or special characters, e.g. `` `total marks` ``.   
- Supported operators: `&` (and), `|` (or), `~` (not), `>`, `>=`, `<`, `<=`, `==`.
- Use **`@`** to reference Python variables in the expression. 
- **Chained comparisons** like `50 <= score <= 90` are allowed.

---

## ✅ Advantages

- Cleaner, more readable filtering syntax. 
- Avoids repetitive `df[...]` patterns.  
- Works well with complex, multi-condition filters.

In [84]:
#filtering data using query

new2=data.query("aqi == 100 & temperature >30 | country == 'US'")[["city","country","aqi"]]

aqi_value=60
new3=data.query("aqi == @aqi_value & temperature >30 & country == 'US'")[["city","country","aqi"]]  #using variable with @
print(new3)

              city country  aqi
416    Los Angeles      US   60
15488      Chicago      US   60
15758      Chicago      US   60
15816      Chicago      US   60
15986      Houston      US   60

In [3]:
#cleaning the data

df=pd.read_csv("raw_data.csv")

In [107]:
print(df.isnull())
print("\n")

print(df)
print("\n")

print(df.isnull().sum())
print("\n")

print(df.fillna(0)) #will fill empty with value .fillna(value)
print("\n")

print(df.dropna())  #raw 
print(df.dropna(axis=1),"\n") #columns (1=true,0=flase)

dt=df.ffill().copy() #forward fill (will fill from above value)
print(dt,"\n")
print(dt.bfill()) #backword fill (will fill from below value)

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False


    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0


id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64


    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6             0  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0


   id        name   age country  gender   income
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
5   5      Li Wei  27.0   China    Male  51000.0
8   8  Rachel Lee  29.0     USA  Female  62000.0
    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [136]:
#duplicate 
dt=df
duplicate=dt.duplicated()
dt["country"].duplicated()

dt.drop_duplicates()

# print(dt)

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [166]:
#datatypes in data
dt=dt.fillna(0)
dt["age"]=dt["age"].astype("int64")
dt.dtypes

date="2025-12-21"
type(date)
date1=pd.Series([pd.to_datetime("2025-12-21")])  #convert to date and time format
type(date1[0])

pandas._libs.tslibs.timestamps.Timestamp

# Pandas

## Cleaning Data

### Handle Strings

- `.str.lower()`, `.str.upper()` & `.capitalize()`
- `.str.strip()`
- `.str.split(" ")`
- `.str.contains(val, case=False)`

In [178]:
dt["gender"].str.lower()
dt["gender"].str.upper()
dt["gender"].str.capitalize()
dt["gender"].str.strip()  #remove sapce
dt["country"].str.contains("usa",case=False)  #if case=false it will check for both lower+upper, but if it is true then it check for exact match

0      True
1      True
2     False
3      True
4     False
5     False
6     False
7       NaN
8      True
9     False
10     True
Name: country, dtype: object

In [2]:
dt=df.copy()
dt["tax"]=dt["income"].apply(lambda x: "30%" if x>=50000 else "10%") #apply(function) where apply is higher order function



gen={"Male":"M","Female":"F","Unknown":"U"}
dt["gender"]=dt["gender"].map(gen)   #map is use to map data

dt.assign(new_income=dt["income"] * 1.1)  #assign is use to assign values, but it will not reflect in real data we need to do it manuall

dt.replace("USA","US")  #replce(old,new)

NameError: name 'df' is not defined

In [17]:
dt.assign(new_income=dt["income"] * 1.1)

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0     USA      M  55000.0  30%     60500.0
1    1      John Doe  29.0     USA      M  55000.0  30%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  30%     68200.0
3    3          Alex   NaN     USA      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  30%     56100.0
6    6           NaN  45.0   India      F  73000.0  30%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  30%     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0  30%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  30%     63800.0

In [30]:
df[["name","age","country","gender","income"]]

            name   age country   gender   income
0       John Doe  29.0     USA     Male  55000.0
1       John Doe  29.0     USA     Male  55000.0
2     Jane Smith   NaN  Canada   Female  62000.0
3           Alex   NaN     USA  Unknown  47000.0
4   Maria Garcia  34.0   Spain   Female      NaN
5         Li Wei  27.0   China     Male  51000.0
6            NaN  45.0   India   Female  73000.0
7     Ahmed Khan  38.0     NaN     Male  68000.0
8     Rachel Lee  29.0     USA   Female  62000.0
9    Carlos Ruiz   NaN  Mexico     Male  45000.0
10   Emily Davis  31.0     USA      NaN  58000.0

In [13]:
df=df.sort_values("income")
df=df.reset_index(drop=True)
df.to_csv("newdata.csv",index=False)

In [28]:
df.groupby("country")["income"].mean()
df.groupby("country")["income"].sum()

df.groupby("country")["income"].agg(["max","mean","min","sum"])

df.groupby("country").agg({
    "income":"max",
    "age":"mean",
})

df.groupby("country").agg(
    Max_income=("income","max"),
    Mean_age=("age","mean"),
)

         Max_income  Mean_age
country
Canada      62000.0       NaN
China       51000.0      27.0
India       73000.0      45.0
Mexico      45000.0       NaN
Spain           NaN      34.0
USA         62000.0      29.5